/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103136-g82123e133d-20210805"
#endif /* AVUTIL_FFVERSION_H */
